### ISSUE TITLE
Crash in various stages of pem generation (`sysread_nonblock': end of file reached (Faraday::ConnectionFailed))

### ISSUE THREAD

**Issue by muffe** [fastlane/pem#66]
I've gotten that error so far when logging in, when choosing my team and when generating the CSR.
Heres a sample console output:

```
[10:59:58]: Existing push notification profile 'MyApp' is valid for 23 more days.
[10:59:58]: Creating a new push certificate for app 'de.myApp'.
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:175:in `sysread_nonblock': end of file reached (Faraday::ConnectionFailed)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:175:in `read_nonblock'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:153:in `rbuf_fill'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:144:in `readline'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:39:in `read_status_line'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:28:in `read_new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1406:in `block in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1376:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1369:in `block in request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1367:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.3/lib/spaceship/client.rb:229:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.3/lib/spaceship/client.rb:161:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.3/lib/spaceship/client.rb:161:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.3/lib/spaceship/client.rb:228:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.3/lib/spaceship/client.rb:204:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.3/lib/spaceship/portal/portal_client.rb:96:in `block in apps'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.3/lib/spaceship/client.rb:113:in `block in paging'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.3/lib/spaceship/client.rb:111:in `loop'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.3/lib/spaceship/client.rb:111:in `paging'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.3/lib/spaceship/portal/portal_client.rb:95:in `apps'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.3/lib/spaceship/portal/app.rb:80:in `all'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.3/lib/spaceship/portal/app.rb:103:in `find'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.5.3/lib/spaceship/portal/certificate.rb:236:in `create!'
	from /Library/Ruby/Gems/2.0.0/gems/pem-0.7.1/lib/pem/manager.rb:37:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/pem-0.7.1/bin/pem:34:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/pem-0.7.1/bin/pem:40:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/pem-0.7.1/bin/pem:46:in `<top (required)>'
	from /usr/bin/pem:23:in `load'
	from /usr/bin/pem:23:in `<main>'
```

**Comment by snatchev** [comment]
@muffe, I believe this is due to intermittent network problems when talking to Apple's servers. Perhaps we can add some retry logic. At the very  least, we can improve the error messaging.

Thanks for reporting.
