### ISSUE TITLE
OpenSSL error when trying to renew

### ISSUE THREAD

**Issue by doapp-ryanp** [fastlane/pem#88]
I have crash reports enabled, here is the id: `ed0f8bbdadf7221c0a6d61780a21fe26`

Getting error:
`OpenSSL::PKey::RSAError: BN lib`

```
fastlane --version
fastlane 1.59.0
pem --version
pem 1.2.0

openssl version -a
OpenSSL 0.9.8zg 14 July 2015
built on: Jul 16 2015
platform: darwin64-x86_64-llvm
options:  bn(64,64) md2(int) rc4(ptr,char) des(idx,cisc,16,int) blowfish(idx)
compiler: -arch x86_64 -fmessage-length=0 -pipe -Wno-trigraphs -fpascal-strings -fasm-blocks -O3 -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DL_ENDIAN -DMD32_REG_T=int -DOPENSSL_NO_IDEA -DOPENSSL_PIC -DOPENSSL_THREADS -DZLIB -mmacosx-version-min=10.6
OPENSSLDIR: "/System/Library/OpenSSL"
```

```
pem --verbose --generate_p12 -u 'me@me.com' --app_identifier 'my.valid.id' --team_id 'TEAMID' -p 'mypw'  --force"
Using /Users/dbuilder/.rvm/gems/ruby-2.2.2
+------------------+---------------------------+
|            Summary for PEM 1.2.0             |
+------------------+---------------------------+
| development      | false                     |
| generate_p12     | true                      |
| force            | true                      |
| save_private_key | true                      |
| app_identifier   | my.valid.id         |
| username         | me@me.com |
| team_id          | TEAMID                |
| p12_password     | mypw                |
| output_path      | .                         |
+------------------+---------------------------+

INFO [2016-02-17 09:36:34.39]: Starting login with user 'me@me.com'
INFO [2016-02-17 09:36:35.62]: Successfully logged in
WARN [2016-02-17 09:36:36.01]: [33mCreating a new push certificate for app 'XXXX'.[0m
[33mSuccessfully submitted a crash report. If this is a problem with one of the tools specifically,[0m
[33mplease submit an issue on GitHub and attach the following number to it: 'ed0f8bbdadf7221c0a6d61780a21fe26'[0m
[33mThe crash report has been stored locally '/tmp/sentry_ed0f8bbdadf7221c0a6d61780a21fe26.json'[0m
/Users/dbuilder/.rvm/gems/ruby-2.2.2@global/gems/spaceship-0.19.4/lib/spaceship/portal/certificate.rb:182:in `initialize': [31m[!] BN lib[0m (OpenSSL::PKey::RSAError)
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2@global/gems/spaceship-0.19.4/lib/spaceship/portal/certificate.rb:182:in `new'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2@global/gems/spaceship-0.19.4/lib/spaceship/portal/certificate.rb:182:in `create_certificate_signing_request'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2@global/gems/pem-1.2.0/lib/pem/manager.rb:44:in `create_certificate'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2@global/gems/pem-1.2.0/lib/pem/manager.rb:30:in `start'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2@global/gems/pem-1.2.0/bin/pem:33:in `block (2 levels) in run'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2@global/gems/fastlane_core-0.36.4/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2@global/gems/pem-1.2.0/bin/pem:39:in `run'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2@global/gems/pem-1.2.0/bin/pem:45:in `<top (required)>'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2/bin/pem:23:in `load'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2/bin/pem:23:in `<main>'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

Any idea what could be going wrong here?  Thanks in advance

**Comment by MickeyHub** [comment]
Hey, @doapp-ryanp , have you try update your openssl.
https://github.com/fastlane/fastlane/blob/master/docs/FAQs.md#im-getting-an-ssl-error
